### ISSUE TITLE
Kansas City, Missouri needs FIPS remapping

### ISSUE THREAD

**Issue by nathansgreen** [schnerd/covid-tracker#1]
FIPS remapping is not implemented for Kansas City, Missouri, which breaks the [Per 100k People](https://www.us-covid-tracker.com/?per100k=1&state=Missouri) feature. The [geographic exceptions](https://github.com/nytimes/covid-19-data#geographic-exceptions) note indicates that KCMO cases are separate from the 4 counties that the city's boundaries fall within. The source CSV does not assign a FIPS code for this data at all, which is probably why it disappears during adjustment. Injecting a fake code such as 29000 or 29998 is one possible way to make this work.

**Comment by schnerd** [comment]
Ahhh yeah I had come across the Kansas City exception when building the new map, but it didn't cross my mind that this also affects per-100k – nice catch! 

I can add an edge case for Kansas City to a fake fips+population, however the other 4 counties will still have inaccurate "per 100k" values since I can't find the non-KC population for each to use as an override. Let me know if you have any ideas here.

**Comment by schnerd** [comment]
@nathansgreen which population value do you think is the most accurate for the rows attributed to "Kansas City"?

![image](https://user-images.githubusercontent.com/875591/78301556-1b765600-74ee-11ea-939a-9985931dcd7e.png)

I'm tempted to go with 491,918, as I'm assuming that the areas outside the city are what they are attributing to the other counties, however I'm not 100% certain.

**Comment by schnerd** [comment]
Quick fix deployed:

![image](https://user-images.githubusercontent.com/875591/78302953-a9ebd700-74f0-11ea-8890-eeba8b1b5320.png)

I'll wait to close this to see if any other thoughts pop up.

**Comment by nathansgreen** [comment]
The 2018 estimate is more accurate. It's probably over 500,000 at this point. If I have time later I'll try to dig through some voting or census data to get an idea of how many residents there are in each of the 4 counties.

**Comment by nathansgreen** [comment]
The mayor has a per-county population estimate here: https://twitter.com/QuintonLucasKC/status/1249756319805997058

**Comment by schnerd** [comment]
@nathansgreen awesome! just updated, let me know if anything looks funky.
