### ISSUE TITLE
Time series plot is blank for total deaths, total cases when using "all time"

### ISSUE THREAD

**Issue by ajakef** [schnerd/covid-tracker#10]
The map still works though. This pattern seems to hold nationwide and at the state level. Example: https://www.us-covid-tracker.com/?field=cases&time=all

Having checked out src/main.js, I can't find the problem and don't have the javascript chops to investigate the issue myself.

**Comment by schnerd** [comment]
@ajakef thanks for the heads up, looking into this

**Comment by schnerd** [comment]
should be fixed now!
