### ISSUE TITLE
County Populations for Missouri for Per 100k is Broken

### ISSUE THREAD

**Issue by nathansgreen** [schnerd/covid-tracker#2]
When [Per 100k is selected for Missouri](https://www.us-covid-tracker.com/?field=cases&time=all&state=Missouri&per100k=1&log=0) all of the data gets dumped into Cass County. Things are slightly better when log scale is selected. I think the change for #1 is what caused the issue.

The Kansas City portion of Cass County is population 85, but the [whole county](https://worldpopulationreview.com/us-counties/mo/cass-county-population/) population is 104,954. The Kansas City total of 85 should be deducted from that number instead of being used for the county population.

**Comment by schnerd** [comment]
I completely misunderstood the tweet you posted in the previous issue. I assumed that "City 505,604" was the population of Kansas City, including the parts that overlap the four counties, and that the figures provided for the other four counties – such has 85 for Cass – meant that was the population of the county that did not reside in Kansas City. It was not immediately clear from the tweet that the "City" was the sum of the four counties.

Will roll out a fix now.

**Comment by schnerd** [comment]
Deployed a fix, want to take a look and see if things are alright?

![image](https://user-images.githubusercontent.com/875591/79384506-dace0200-7f1b-11ea-9083-b9a951caa008.png)

**Comment by nathansgreen** [comment]
I think the fix worked. The city population is the sum of the numbers from the tweet, so those numbers get subtracted from those four counties. It's confusing. Thank you!
