### ISSUE TITLE
Plot gradient of log chart?

### ISSUE THREAD

**Issue by O1O1O1O** [schnerd/covid-tracker#4]
I'm loving the new 7 day moving averages - really helpful to make sense of the noisy daily numbers, especially in smaller states and most counties.  

To further aid interpretation of the charts how about you add a gradient of log scale charts for total numbers?  I ask because sometimes it is hard to tell if the log charts are increasing or decreasing their slope.

**Comment by schnerd** [comment]
Thanks for reaching out! Can you provide an example/screenshot/mockup of what you mean by "gradient of log scale"? I agree it can be hard to see the slope.
